### ISSUE TITLE
Could you add a cluster please?

### ISSUE THREAD

**Issue by sequensucks** [AmrSaber/simple-redis-mutex#9]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `simple-redis-mutex@1.1.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/simple-redis-mutex/index.d.ts b/node_modules/simple-redis-mutex/index.d.ts
index ab22b7c..3c7e918 100644
--- a/node_modules/simple-redis-mutex/index.d.ts
+++ b/node_modules/simple-redis-mutex/index.d.ts
@@ -1,4 +1,4 @@
-import { Redis } from 'ioredis';
+import { Redis, Cluster } from 'ioredis';
 
 /**
  * Release the lock only if it has the same lockValue as acquireLock sets it.
@@ -36,7 +36,7 @@ interface acquireOptions {
  * @returns a promise that resolves with release function.
  */
 export function lock(
-  client: Redis,
+  client: Redis | Cluster,
   lockName: string,
   options: acquireOptions
 ): Promise<ReleaseFunction>;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by AmrSaber** [comment]
Hello @sequensucks 
I don't see why not, as long as it's only in the types. Would be interested to make the PR yourself since you basically wrote the code for it?

But note that this won't use the fault tolerance of the cluster, meaning that if the node that had the info broke down, then we won't be able to tell if the lock is acquired or not. For better fault tolerance with redis cluster, checkout out the more sophisticated solution [redlock](https://www.npmjs.com/package/redlock).
